### PR TITLE
Hot Fix: Successful Response with Encrypted password

### LINKED ISSUE #26: Request with Password Param Failing
I created a simple form iOS form app just to see how well Swift can handle HTTP requests to our backend server. I've tested our API on Postman on the browser and it's completely functional with no errors. A problem arises when we send JSON from the Swift programming language.

Here are some testing I did to see the problem:
Capture
Above, are two requests I sent out to the backend. The only difference between the two is when I deleted the parameter for password.

Here's a [stackoverflow problem](https://stackoverflow.com/questions/52982858/illegal-arguments-undefined-string) I found on this. I followed all the following fixes stated, but no success.

Should we lose the encryption process of the JS?

### PR DESCRIPTION
**Pull request by lsalazar1**
Ref. Issue #26 

The backend can now encrypt the "password" field without failing. The Swift code must have:

`request.addValue("application/json", forHTTPHeaderField: "Content-Type")`

The reason why we had an issue with this is because when our backend receives the json from frontend, it was thinking it was getting a "Content-Type: application/html". The frontend is also expecting a json back, so this commit returned exactly that.

### CODE REVIEW

**Review by mariahfont — APPROVED** [review]

**Review by gazie91 — APPROVED** [review]
Nice job bro

**Comment by lsalazar1** [comment]
Thanks man, that was a headache lol

File: routes/apis/users.js [hunk 1]
```diff
@@ -23,9 +23,7 @@ router.post(
     ],
     async (req, res) => {
         const errors = validationResult(req);
-
-        console.log('Test');
-        console.log(req.query);
+        
         // If there are any errors found by validationResult in user's HTTP request, we'll return an HTTP status code 400
         // with an array of errors found
```
Comment (mbghazi) [inline routes/apis/users.js:28]: Is there any situation where we need to account for 404 error? Disconnection from server?

**Review by mbghazi — APPROVED** [review]

File: routes/apis/users.js (hunk 1 above)
Comment (lsalazar1) [reply routes/apis/users.js:28]: It's really up to us how to handle our errors. If you look at the try-catch statement I wrote out, I use a Error 500 instead of a 404 if I can't make a connection with the server.

**Review by rouoba — APPROVED** [review]
Nice job!
